name: HexCoin
version: '${project.version}'
main: me.thegoldenmine.com.hamstercoin.HexCoin
api-version: 1.16
authors: [ TheGoldenMine ]
description: A simple coin plugin
website: https://www.spigotmc.org/members/thegoldenmine.1437483/
commands:
  payhex:
    description: You can pay coins to others
    usage: /payhex <playername> <money>
    permission-message: You don't have permission to use this command
    permission: hex.pay
  resethex:
    description: Sets the coins to zero
    usage: /resethex <playername>
    permission-message: You don't have permission to use this command
    permission: hex.reset
  sethex:
    description: Sets the amount of coins to player
    usage: /sethex <playername> <money>
    permission-message: You don't have permission to use this command
    permission: hex.set
  givehex:
    description: Give some money to player without paying
    usage: /givehex <playername> <money>
    permission-message: You don't have permission to use this command
    permission: hex.give
  balhex:
    description: You can see your balance
    usage: /balhex
    permission: hex.bal
    permission-message: You don't have permission to use this command
  reloadhex:
    description: You can reload the config
    usage: /reloadhex
    permission: hex.reload
    permission-message: You don't have permission to use this command
  takehex:
    description: You can take hex from players
    usage: /takehex <playername> <money>
    permission: hex.take
    permission-message: You don't have permission to use this command
permissions:
  hex.take:
    description: You can use /takehex
    default: op
  hex.reload:
    description: You can use /reloadhex
    default: op
  hex.bal:
    description: You can use /balhex
    default: op
  hex.give:
    description: You can give money to players without paying
    default: op
  hex.set:
    description: You can use command /sethex
    default: op
  hex.pay:
    default: op
    description: You can use command /payhex
  hex.reset:
    default: op
    description: You can use command /resethex